[test]
root = "./__tests__"
preload = ["./setup.ts"]
coverage = false 
coverageReporter  = ["text", "lcov"]
[install]
# configuration here
dev = true
peer = true
production = false #toggle this for production 
auto = "auto" # "fallback"
[run]
# default outside of Windows

shell = "system" 
# Uncomment For Windows 
# shell="bun"

# equivalent to `bun --bun` for all `bun run` commands
bun = true