blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/your-org/your-repo/discussions
    about: Use GitHub Discussions for questions and help
  - name: 💬 Community Chat
    url: https://discord.gg/your-discord
    about: Join our community chat for real-time discussions
  - name: 📖 Documentation
    url: https://your-docs-site.com
    about: Check our documentation for guides and references
