name: 📚 Documentation
description: Report an issue related to documentation
title: '[Docs]: '
labels: ['documentation']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve our documentation!
  - type: dropdown
    id: type
    attributes:
      label: Type of documentation issue
      options:
        - Missing documentation
        - Outdated documentation
        - Incorrect documentation
        - Unclear documentation
        - Other
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Documentation location
      description: Where is the documentation you're referring to?
      placeholder: 'e.g., /docs/api/authentication.md or API Authentication page'
  - type: textarea
    id: description
    attributes:
      label: What's the issue?
      description: Describe what's wrong or missing in the documentation
      placeholder: The authentication example is missing information about refresh tokens...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested changes
      description: If you have specific suggestions for how to improve the documentation, please share them
      placeholder: |
        Here's how I would word this section:
        ...
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
